import {
  IsBoolean,
  IsOptional,
  IsString,
  MaxLength,
} from 'class-validator';

export class CreateAttributeValueDto {
  @IsString()
  @MaxLength(100)
  name!: string;

  // Manual SKU entered by user
  @IsOptional()
  @IsString()
  @MaxLength(10)
  skuCode?: string;

  // DO NOT ADD code HERE
  // code is generated by the backend

  @IsString()
  attributeId!: string;

  @IsOptional()
  @IsString()
  @MaxLength(255)
  description?: string;

  @IsOptional()
  @IsBoolean()
  isActive?: boolean;
}